/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package final_exam.dialogs.category;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

import final_exam.utils.SQLConfig;

/**
 * Save dialog for adding new categories.
 */
public class SaveCategoryDialog extends javax.swing.JDialog {

    /**
     * Creates new form SaveCategoryDialog
     */
    public SaveCategoryDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel3 = new javax.swing.JLabel();
        Container = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        categoryNameField = new javax.swing.JTextField();
        cancelButton1 = new javax.swing.JButton();
        saveNewButton = new javax.swing.JButton();
        offsetR = new javax.swing.JPanel();

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Category Name:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Container.setBackground(new java.awt.Color(255, 255, 255));
        Container.setMaximumSize(new java.awt.Dimension(410, 370));
        Container.setMinimumSize(new java.awt.Dimension(410, 370));
        Container.setPreferredSize(new java.awt.Dimension(410, 370));
        Container.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CATEGORY");
        jLabel4.setMaximumSize(new java.awt.Dimension(410, 48));
        jLabel4.setMinimumSize(new java.awt.Dimension(410, 48));
        jLabel4.setPreferredSize(new java.awt.Dimension(410, 48));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 50, 0);
        Container.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Category Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 0);
        Container.add(jLabel5, gridBagConstraints);

        categoryNameField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        categoryNameField.setForeground(new java.awt.Color(51, 51, 51));
        categoryNameField.setMaximumSize(new java.awt.Dimension(320, 32));
        categoryNameField.setMinimumSize(new java.awt.Dimension(320, 32));
        categoryNameField.setPreferredSize(new java.awt.Dimension(320, 32));
        categoryNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryNameFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        Container.add(categoryNameField, gridBagConstraints);

        cancelButton1.setBackground(new java.awt.Color(230, 230, 230));
        cancelButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelButton1.setForeground(new java.awt.Color(51, 51, 51));
        cancelButton1.setText("Cancel");
        cancelButton1.setBorderPainted(false);
        cancelButton1.setMaximumSize(new java.awt.Dimension(160, 32));
        cancelButton1.setMinimumSize(new java.awt.Dimension(160, 32));
        cancelButton1.setPreferredSize(new java.awt.Dimension(160, 32));
        cancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(80, 42, 80, 5);
        Container.add(cancelButton1, gridBagConstraints);

        saveNewButton.setBackground(new java.awt.Color(0, 153, 153));
        saveNewButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        saveNewButton.setForeground(new java.awt.Color(255, 255, 255));
        saveNewButton.setText("Save New");
        saveNewButton.setBorderPainted(false);
        saveNewButton.setMaximumSize(new java.awt.Dimension(160, 32));
        saveNewButton.setMinimumSize(new java.awt.Dimension(160, 32));
        saveNewButton.setPreferredSize(new java.awt.Dimension(160, 32));
        saveNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNewButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(80, 5, 80, 42);
        Container.add(saveNewButton, gridBagConstraints);

        javax.swing.GroupLayout offsetRLayout = new javax.swing.GroupLayout(offsetR);
        offsetR.setLayout(offsetRLayout);
        offsetRLayout.setHorizontalGroup(
            offsetRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        offsetRLayout.setVerticalGroup(
            offsetRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        Container.add(offsetR, gridBagConstraints);

        getContentPane().add(Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void categoryNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryNameFieldActionPerformed

    private void cancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButton1ActionPerformed

    private void saveNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNewButtonActionPerformed
        String categoryName = categoryNameField.getText();
        
        if (categoryName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill out all the necessary fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try (Connection con = getConnection();
            PreparedStatement pstmt = con.prepareStatement("INSERT INTO Categories (category_name) VALUES (?)")) {
            pstmt.setString(1, categoryName);
            pstmt.executeUpdate();
            dispose();
        } catch (SQLException | ClassNotFoundException e) {
            showError(e);
        }
    }//GEN-LAST:event_saveNewButtonActionPerformed

    private Connection getConnection() throws SQLException, ClassNotFoundException {
        SQLConfig sql = new SQLConfig();
        String DB_URL = sql.getDbUrl();
        String DB_USER = sql.getDbUser();
        String DB_PASSWORD = sql.getDbPassword();
        Class.forName("com.mysql.cj.jdbc.Driver");
        return DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
    }

    private void showError(Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaveCategoryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaveCategoryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaveCategoryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaveCategoryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaveCategoryDialog dialog = new SaveCategoryDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JButton cancelButton1;
    private javax.swing.JTextField categoryNameField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel offsetR;
    private javax.swing.JButton saveNewButton;
    // End of variables declaration//GEN-END:variables
}