/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package final_exam.dialogs.supplier;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

import final_exam.utils.SQLConfig;

/**
 * Edit dialog for editing categories.
 */
public class EditSupplierDialog extends javax.swing.JDialog {
    private int id;

    public EditSupplierDialog(java.awt.Frame parent, boolean modal, int id, String... values) {
        super(parent, modal);
        this.id = id;
        initComponents();
        supplierNameField.setText(values[0]);
        contactInfoField.setText(values[1]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Container = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        supplierNameField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        saveChangesButton = new javax.swing.JButton();
        offsetR = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        contactInfoField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(410, 460));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Container.setBackground(new java.awt.Color(255, 255, 255));
        Container.setMaximumSize(new java.awt.Dimension(410, 460));
        Container.setMinimumSize(new java.awt.Dimension(410, 460));
        Container.setPreferredSize(new java.awt.Dimension(410, 460));
        Container.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SUPPLIER");
        jLabel1.setMaximumSize(new java.awt.Dimension(410, 48));
        jLabel1.setMinimumSize(new java.awt.Dimension(410, 48));
        jLabel1.setPreferredSize(new java.awt.Dimension(410, 48));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 50, 0);
        Container.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("New Supplier Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 0);
        Container.add(jLabel2, gridBagConstraints);

        supplierNameField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        supplierNameField.setForeground(new java.awt.Color(51, 51, 51));
        supplierNameField.setMaximumSize(new java.awt.Dimension(320, 32));
        supplierNameField.setMinimumSize(new java.awt.Dimension(320, 32));
        supplierNameField.setPreferredSize(new java.awt.Dimension(320, 32));
        supplierNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierNameFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        Container.add(supplierNameField, gridBagConstraints);

        cancelButton.setBackground(new java.awt.Color(230, 230, 230));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(51, 51, 51));
        cancelButton.setText("Cancel");
        cancelButton.setBorderPainted(false);
        cancelButton.setMaximumSize(new java.awt.Dimension(160, 32));
        cancelButton.setMinimumSize(new java.awt.Dimension(160, 32));
        cancelButton.setPreferredSize(new java.awt.Dimension(160, 32));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(80, 42, 80, 5);
        Container.add(cancelButton, gridBagConstraints);

        saveChangesButton.setBackground(new java.awt.Color(0, 153, 153));
        saveChangesButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        saveChangesButton.setForeground(new java.awt.Color(255, 255, 255));
        saveChangesButton.setText("Save Changes");
        saveChangesButton.setBorderPainted(false);
        saveChangesButton.setMaximumSize(new java.awt.Dimension(160, 32));
        saveChangesButton.setMinimumSize(new java.awt.Dimension(160, 32));
        saveChangesButton.setPreferredSize(new java.awt.Dimension(160, 32));
        saveChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(80, 5, 80, 42);
        Container.add(saveChangesButton, gridBagConstraints);

        offsetR.setBackground(new Color(0,0,0,0));

        javax.swing.GroupLayout offsetRLayout = new javax.swing.GroupLayout(offsetR);
        offsetR.setLayout(offsetRLayout);
        offsetRLayout.setHorizontalGroup(
            offsetRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        offsetRLayout.setVerticalGroup(
            offsetRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        Container.add(offsetR, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("New Contact Information:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 50, 0, 0);
        Container.add(jLabel3, gridBagConstraints);

        contactInfoField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        contactInfoField.setForeground(new java.awt.Color(51, 51, 51));
        contactInfoField.setMaximumSize(new java.awt.Dimension(320, 32));
        contactInfoField.setMinimumSize(new java.awt.Dimension(320, 32));
        contactInfoField.setPreferredSize(new java.awt.Dimension(320, 32));
        contactInfoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactInfoFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        Container.add(contactInfoField, gridBagConstraints);

        getContentPane().add(Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void supplierNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierNameFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesButtonActionPerformed
        String newSupplierName = supplierNameField.getText();
        String newContactInfo = contactInfoField.getText();
        
        if (newSupplierName.isEmpty() || newContactInfo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill out all the necessary fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try (Connection con = getConnection();
             PreparedStatement pstmt = con.prepareStatement("UPDATE Suppliers SET category_name = ?, contact_info = ? WHERE supplier_id = ?")) {
            pstmt.setString(1, newSupplierName);
            pstmt.setString(2, newContactInfo);
            pstmt.setInt(3, id);
            pstmt.executeUpdate();
            dispose();
        } catch (SQLException | ClassNotFoundException e) {
            showError(e);
        }
    }//GEN-LAST:event_saveChangesButtonActionPerformed

    private void contactInfoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactInfoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactInfoFieldActionPerformed

    private Connection getConnection() throws SQLException, ClassNotFoundException {
        SQLConfig sql = new SQLConfig();
        String DB_URL = sql.getDbUrl();
        String DB_USER = sql.getDbUser();
        String DB_PASSWORD = sql.getDbPassword();
        Class.forName("com.mysql.cj.jdbc.Driver");
        return DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
    }

    private void showError(Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditSupplierDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditSupplierDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditSupplierDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditSupplierDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditSupplierDialog dialog = new EditSupplierDialog(new javax.swing.JFrame(), true, 1, "v0");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField contactInfoField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel offsetR;
    private javax.swing.JButton saveChangesButton;
    private javax.swing.JTextField supplierNameField;
    // End of variables declaration//GEN-END:variables
}