/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package final_exam.dialogs.transaction;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

import final_exam.utils.SQLConfig;
/**
 *
 * @author Kaiyou
 */
public class DeleteTransactionDialog extends javax.swing.JDialog {
    private int id;

    public DeleteTransactionDialog(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        this.id = id;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Container = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        confirmDeleteButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        offsetR = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(410, 360));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Container.setBackground(new java.awt.Color(255, 255, 255));
        Container.setMaximumSize(new java.awt.Dimension(410, 360));
        Container.setMinimumSize(new java.awt.Dimension(410, 360));
        Container.setPreferredSize(new java.awt.Dimension(410, 360));
        Container.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 63, 25));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRANSACTION");
        jLabel1.setMaximumSize(new java.awt.Dimension(410, 48));
        jLabel1.setMinimumSize(new java.awt.Dimension(410, 48));
        jLabel1.setPreferredSize(new java.awt.Dimension(410, 48));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 50, 0);
        Container.add(jLabel1, gridBagConstraints);

        cancelButton.setBackground(new java.awt.Color(230, 230, 230));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(51, 51, 51));
        cancelButton.setText("Cancel");
        cancelButton.setBorderPainted(false);
        cancelButton.setMaximumSize(new java.awt.Dimension(160, 32));
        cancelButton.setMinimumSize(new java.awt.Dimension(160, 32));
        cancelButton.setPreferredSize(new java.awt.Dimension(160, 32));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(80, 42, 80, 5);
        Container.add(cancelButton, gridBagConstraints);

        confirmDeleteButton.setBackground(new java.awt.Color(250, 63, 25));
        confirmDeleteButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        confirmDeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmDeleteButton.setText("Confirm Delete");
        confirmDeleteButton.setBorderPainted(false);
        confirmDeleteButton.setMaximumSize(new java.awt.Dimension(160, 32));
        confirmDeleteButton.setMinimumSize(new java.awt.Dimension(160, 32));
        confirmDeleteButton.setPreferredSize(new java.awt.Dimension(160, 32));
        confirmDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmDeleteButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(80, 5, 80, 42);
        Container.add(confirmDeleteButton, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("This can't be undone.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        Container.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Confirm delete?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        Container.add(jLabel4, gridBagConstraints);

        javax.swing.GroupLayout offsetRLayout = new javax.swing.GroupLayout(offsetR);
        offsetR.setLayout(offsetRLayout);
        offsetRLayout.setHorizontalGroup(
            offsetRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        offsetRLayout.setVerticalGroup(
            offsetRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        Container.add(offsetR, gridBagConstraints);

        getContentPane().add(Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void confirmDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmDeleteButtonActionPerformed
        String selectTransactionQuery = "SELECT item_id, quantity, transaction_type FROM Transactions WHERE transaction_id = ?";
        String selectItemQuery = "SELECT quantity_on_hand FROM Items where item_id = ?";
        String deleteTransactionQuery = "DELETE FROM Transactions WHERE transaction_id = ?";
        String updateItemQuantityQuery = "UPDATE Items SET quantity_on_hand = ? WHERE item_id = ?";

        try (Connection con = getConnection()) {
            con.setAutoCommit(false); // Start transaction

            int itemId = 0;
            int transactionQuantity = 0;
            String transactionType = "";

            try (PreparedStatement selectStmt = con.prepareStatement(selectTransactionQuery)) {
                selectStmt.setInt(1, id);
                ResultSet rs = selectStmt.executeQuery();
                if (rs.next()) {
                    itemId = rs.getInt("item_id");
                    transactionQuantity = rs.getInt("quantity");
                    transactionType = rs.getString("transaction_type");
                } else {
                    JOptionPane.showMessageDialog(this, "Transaction not found.", "Error", JOptionPane.ERROR_MESSAGE);
                    con.rollback();
                    return;
                }
            }
            
            int itemQuantity = 0;
            try (PreparedStatement selectStmt = con.prepareStatement(selectItemQuery)) {
                selectStmt.setInt(1, itemId);
                ResultSet rs = selectStmt.executeQuery();
                if (rs.next()) {
                    itemQuantity = rs.getInt("quantity_on_hand");
                } else {
                    JOptionPane.showMessageDialog(this, "Item not found.", "Error", JOptionPane.ERROR_MESSAGE);
                    con.rollback();
                    return;
                }
            }
            int newQuantity = itemQuantity;
            if ("Stock in".equalsIgnoreCase(transactionType)) {
                newQuantity -= transactionQuantity;
            } else if ("Stock out".equalsIgnoreCase(transactionType)) {
                newQuantity += transactionQuantity;
            }

            if (newQuantity < 0) {
                JOptionPane.showMessageDialog(this, "Deletion would result to a negative stock value.", "Error", JOptionPane.ERROR_MESSAGE);
                con.rollback();
                return;
            }

            try (PreparedStatement updateItemStmt = con.prepareStatement(updateItemQuantityQuery)) {
                updateItemStmt.setInt(1, newQuantity);
                updateItemStmt.setInt(2, itemId);
                updateItemStmt.executeUpdate();
            }

            try (PreparedStatement deleteStmt = con.prepareStatement(deleteTransactionQuery)) {
                deleteStmt.setInt(1, id);
                deleteStmt.executeUpdate();
            }

            con.commit();
            JOptionPane.showMessageDialog(this, "Transaction deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (Exception e) {
            showError(e);
        }
    }//GEN-LAST:event_confirmDeleteButtonActionPerformed

    private Connection getConnection() throws SQLException, ClassNotFoundException {
        SQLConfig sql = new SQLConfig();
        String DB_URL = sql.getDbUrl();
        String DB_USER = sql.getDbUser();
        String DB_PASSWORD = sql.getDbPassword();
        Class.forName("com.mysql.cj.jdbc.Driver");
        return DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
    }

    private void showError(Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteTransactionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteTransactionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteTransactionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteTransactionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DeleteTransactionDialog dialog = new DeleteTransactionDialog(new javax.swing.JFrame(), true, 1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmDeleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel offsetR;
    // End of variables declaration//GEN-END:variables
}
