/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package final_exam.dialogs.purchase;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane; 
import final_exam.utils.SQLConfig;

public class ViewPurchaseDialog extends javax.swing.JDialog {
    private int purchaseOrderId;
    private int maxKeyLength = 11;

    public ViewPurchaseDialog(java.awt.Frame parent, boolean modal, int purchaseOrderId) {
        super(parent, modal);
        this.purchaseOrderId = purchaseOrderId;
        initComponents();
        loadPurchaseInfo();
        loadDataAndDisplay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Container = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        doneButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultLabel = new javax.swing.JLabel();
        purchaseInfoLabel = new javax.swing.JLabel();
        grandTotalLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 900));
        setMinimumSize(new java.awt.Dimension(450, 900));
        setPreferredSize(new java.awt.Dimension(450, 900));
        setResizable(false);

        Container.setBackground(new java.awt.Color(255, 255, 255));
        Container.setMaximumSize(new java.awt.Dimension(410, 600));
        Container.setMinimumSize(new java.awt.Dimension(410, 600));
        Container.setPreferredSize(new java.awt.Dimension(410, 600));
        Container.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PURCHASE ORDER");
        jLabel1.setMaximumSize(new java.awt.Dimension(410, 48));
        jLabel1.setMinimumSize(new java.awt.Dimension(410, 48));
        jLabel1.setPreferredSize(new java.awt.Dimension(410, 48));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 10, 0);
        Container.add(jLabel1, gridBagConstraints);

        doneButton.setBackground(new java.awt.Color(0, 153, 153));
        doneButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        doneButton.setForeground(new java.awt.Color(255, 255, 255));
        doneButton.setText("Done");
        doneButton.setBorderPainted(false);
        doneButton.setMaximumSize(new java.awt.Dimension(160, 32));
        doneButton.setMinimumSize(new java.awt.Dimension(160, 32));
        doneButton.setPreferredSize(new java.awt.Dimension(160, 32));
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(80, 42, 80, 42);
        Container.add(doneButton, gridBagConstraints);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(320, 400));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(320, 400));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(320, 400));
        jScrollPane1.setRequestFocusEnabled(false);

        resultLabel.setBackground(new Color(0,0,0,0));
        resultLabel.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        resultLabel.setForeground(new java.awt.Color(51, 51, 51));
        resultLabel.setText("-");
        resultLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jScrollPane1.setViewportView(resultLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        Container.add(jScrollPane1, gridBagConstraints);

        purchaseInfoLabel.setBackground(new Color(0,0,0,0));
        purchaseInfoLabel.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        purchaseInfoLabel.setForeground(new java.awt.Color(51, 51, 51));
        purchaseInfoLabel.setText("-");
        purchaseInfoLabel.setMaximumSize(new java.awt.Dimension(320, 96));
        purchaseInfoLabel.setMinimumSize(new java.awt.Dimension(320, 96));
        purchaseInfoLabel.setPreferredSize(new java.awt.Dimension(320, 96));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        Container.add(purchaseInfoLabel, gridBagConstraints);

        grandTotalLabel.setBackground(new Color(0,0,0,0));
        grandTotalLabel.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        grandTotalLabel.setForeground(new java.awt.Color(51, 51, 51));
        grandTotalLabel.setText("-");
        grandTotalLabel.setMaximumSize(new java.awt.Dimension(320, 32));
        grandTotalLabel.setMinimumSize(new java.awt.Dimension(320, 32));
        grandTotalLabel.setPreferredSize(new java.awt.Dimension(320, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        Container.add(grandTotalLabel, gridBagConstraints);

        getContentPane().add(Container, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        dispose();
    }//GEN-LAST:event_doneButtonActionPerformed
    
    public void loadPurchaseInfo() {
        String query = "SELECT po.purchase_order_id, po.order_date, s.supplier_name, po.total_amount " +
                       "FROM PurchaseOrders po " +
                       "JOIN Suppliers s ON po.supplier_id = s.supplier_id " +
                       "WHERE po.purchase_order_id = ?;";

        try (Connection con = getConnection();
             PreparedStatement pstmt = con.prepareStatement(query)) {
            
            pstmt.setInt(1, purchaseOrderId);
            ResultSet rs = pstmt.executeQuery();
            
            if (rs.next()) {
                int purchaseOrderId = rs.getInt("purchase_order_id");
                String orderDate = rs.getString("order_date");
                String supplierName = rs.getString("supplier_name");
                double totalAmount = rs.getDouble("total_amount");
                
                StringBuilder purchaseInfo = new StringBuilder();
                purchaseInfo.append(String.format("%-" + (maxKeyLength + 2) + "s:  %d<br>", "Order ID", purchaseOrderId));
                purchaseInfo.append(String.format("%-" + (maxKeyLength + 2) + "s:  %s<br>", "Order Date", orderDate));
                purchaseInfo.append(String.format("%-" + (maxKeyLength + 2) + "s:  %s<br>", "Supplier", supplierName));
                
                purchaseInfoLabel.setFont(new Font("Courier New", Font.PLAIN, 14));
                purchaseInfoLabel.setText("<html>" + purchaseInfo.toString().replace(" ", "&nbsp;") + "</html>");
                
                StringBuilder grandTotal = new StringBuilder();
                grandTotal.append(String.format("%-" + (maxKeyLength + 2) + "s:  %.2f", "GRAND TOTAL", totalAmount));
                grandTotalLabel.setFont(new Font("Courier New", Font.PLAIN, 14));
                grandTotalLabel.setText("<html>" + grandTotal.toString().replace(" ", "&nbsp;") + "</html>");
            }
        } catch (Exception e) {
            showError(e);
        }
    }
    
    public void loadDataAndDisplay() {
        // Query to get purchase order items
        String query = "SELECT poi.purchase_order_item_id, i.item_name, poi.quantity, poi.unit_price " +
                       "FROM PurchaseOrderItems poi " +
                       "JOIN Items i ON poi.item_id = i.item_id " +
                       "WHERE poi.purchase_order_id = ?";
        
        StringBuilder dataBuilder = new StringBuilder();

        try (Connection con = getConnection();
             PreparedStatement pstmt = con.prepareStatement(query)) {
            
            pstmt.setInt(1, purchaseOrderId);
            ResultSet rs = pstmt.executeQuery();
            
            int maxKeyLength = 11;
            while (rs.next()) {
                int purchaseOrderItemId = rs.getInt("purchase_order_item_id");
                String itemName = rs.getString("item_name");
                int quantity = rs.getInt("quantity");
                double unitPrice = rs.getDouble("unit_price");
                double subtotal = quantity * unitPrice;
                dataBuilder.append(String.format("%-" + (maxKeyLength + 2) + "s:  %d<br>", "ID", purchaseOrderItemId));
                dataBuilder.append(String.format("%-" + (maxKeyLength + 2) + "s:  %s<br>", "Item Name", itemName));
                dataBuilder.append(String.format("%-" + (maxKeyLength + 2) + "s:  %d<br>", "Quantity", quantity));
                dataBuilder.append(String.format("%-" + (maxKeyLength + 2) + "s:  %.2f<br>", "Unit Price", unitPrice));
                dataBuilder.append(String.format("%-" + (maxKeyLength + 2) + "s:  %.2f<br><br>", "Subtotal", subtotal));
            }
            
        } catch (Exception e) {
            showError(e);
        }
        
        resultLabel.setFont(new Font("Courier New", Font.PLAIN, 14));
        resultLabel.setText("<html>" + dataBuilder.toString().replace(" ", "&nbsp;") + "</html>");
    }
    
    private Connection getConnection() throws SQLException, ClassNotFoundException {
        SQLConfig sql = new SQLConfig();
        String DB_URL = sql.getDbUrl();
        String DB_USER = sql.getDbUser();
        String DB_PASSWORD = sql.getDbPassword();
        Class.forName("com.mysql.cj.jdbc.Driver");
        return DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
    }

    private void showError(Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPurchaseDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPurchaseDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPurchaseDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPurchaseDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewPurchaseDialog dialog = new ViewPurchaseDialog(new javax.swing.JFrame(), true, 1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JButton doneButton;
    private javax.swing.JLabel grandTotalLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel purchaseInfoLabel;
    private javax.swing.JLabel resultLabel;
    // End of variables declaration//GEN-END:variables
}